<?php

return [
    'style1'    => [
        'steps'     => 2,
        'wrapper_class'     => 'bg-white ',
        'template_wrapper_class'     => 'px-10',
        'width'         => '800px',
        'step_1_top_left_width' => 'wpcm-col-sm-12',
        'step_1_top_right_width' => 'wpcm-col-sm-12',
        'step_1_content_left_width' => 'wpcm-col-sm-12',
        'step_1_content_right_width' => 'wpcm-col-sm-12',
        'step_2_top_left_width' => 'wpcm-col-sm-12',
        'step_2_content_left_width' => 'wpcm-col-sm-12',
        'proceed'       => esc_html__('Proceed', 'lifeline-donation-pro'),
        'donate_now'    => esc_html__('Donate Now', 'lifeline-donation-pro'),
    ],
    'style2'    => [
        'steps'             => 2,
        'wrapper_class'     => 'bg-white',
        'template_wrapper_class'     => 'px-40',
        'width'             => '780px',
        'step_1_top_left_width' => 'wpcm-col-sm-12',
        'step_1_top_right_width' => 'wpcm-col-sm-12',
        'step_1_top_left_width' => 'wpcm-col-sm-12',
        'step_1_top_right_width' => 'wpcm-col-sm-12',
        'step_1_content_left_width' => 'wpcm-col-sm-12',
        'step_1_content_right_width' => 'wpcm-col-sm-12',
        'step_2_top_left_width' => 'wpcm-col-sm-12',
        'step_2_content_left_width' => 'wpcm-col-sm-12',
        'proceed'       => esc_html__('Proceed', 'lifeline-donation-pro'),
        'donate_now'    => esc_html__('Donate Now', 'lifeline-donation-pro'),
        'back_text'    => esc_html__('Go Back', 'lifeline-donation-pro'),
        'show_back_btn'    => true,
    ],
    'style3'    => [
        'steps' => 2,
        'width'             => '800px',
        'wrapper_class'     => 'wpcm-wrapper',
        'template_wrapper_class'     => 'wpcm-container',
        'step_1_top_left_width' => 'wpcm-col-sm-12',
        'step_1_content_left_width' => 'wpcm-col-sm-12',
        'step_2_top_left_width' => 'wpcm-col-sm-12',
        'step_2_content_left_width' => 'wpcm-col-sm-12',
        'back_text'    => esc_html__('Go Back', 'lifeline-donation-pro'),
        'show_back_btn'    => true,
        'proceed'       => esc_html__('Proceed', 'lifeline-donation-pro'),
        'proceed_classes'   => 'donation-done',
        'donate_now'    => esc_html__('Donate Now', 'lifeline-donation-pro'),
    ]
];